<?php
function my_form_menu(){
	$items = array();
	$items['contacts'] = array(
		'title' => t('Contacts'),
		'page callback' => 'form_out',
		'access callback' => TRUE
	);
	$items['success'] = array(
		'page callback' => 'form_out',
		'access callback' => TRUE
		);
	return $items;
}

function my_form_form($form, &$form_state){
	$form = array();
	$form['randon_text'] = array(
  	  '#markup' => t('Hi! You are on Drupal.'),
	);
	$form['name'] = array(
      '#type' => 'textfield',
	  '#title' => t('Name'),
	  '#maxlength' => 128,
	  '#required' => TRUE,
  	);
	$form['surname'] = array(
      '#type' => 'textfield',
	  '#title' => t('Surname'),
	  '#maxlength' => 128,
  	);
	$form['nickname'] = array(
      '#type' => 'textfield',
	  '#title' => t('Nickname'),
	  '#maxlength' => 128,
	  '#required' => TRUE,
  	);
  	$form['email'] = array(
      '#type' => 'textfield',
	  '#title' => t('E-mail'),
	  '#maxlength' => 128,
	  '#required' => TRUE,
  	);
  	$form['phone'] = array(
      '#type' => 'textfield',
	  '#title' => t('Phone'),
	  '#maxlength' => 128,
  	);
  	$active  =array(
  		'Steve Jobs',
  		'England',
  		'Holidays',
  	);
  	$form['article'] = array(
	  '#type' => 'radios',
	  '#title' => t('Select article'),
	  '#default_value' => 1,
	  '#options' => $active,
  	);
  	$countrys = array(
  		'Ukraine',
  		'USA',
  		'Russia',
  	);
  	$form['country'] = array(
	  '#type' => 'select',
	  '#title' => t('Select your country'),
	  '#options' => $countrys,
	  '#default_value' => 1,
  	);
  	$form['message'] = array(
	  '#title' => t('Message'),
 	  '#type' => 'textarea',
 	  '#required' => TRUE,
 	  '#description' => t('This field is required. Please fill it.'),
	);
	$form['agrees'] = array(
	  '#type' => 'checkbox',
	  '#title' => t('I agree with the rules.'),
	);
	$form['random'] = array(
	  '#type' => 'fieldset',
	  '#title' => t('Random Text'),
	  '#description' => t('This is my random text.'),
	  '#collapsible' => TRUE,
	  '#collapsed' => TRUE,
	);
	$form['submit'] = array(
	  '#type' => 'submit',
	  '#value' => t('Send'),

	);
	return $form;
}
function my_form_form_alter(&$form, &$form_state, $form_id) {
	if ($form_id == 'my_form_form'){
	$form['name'] = array(
		'#type' => 'textfield',
		'#title' => t('Your name'),
		'#maxlength' => 128,
	    '#required' => TRUE,
	);
}
}

function form_out(){
	$page = arg(0);
	switch ($page){
		case 'contacts':
			$form = drupal_get_form('my_form_form');
			$form = drupal_render($form);
			break;
		case 'success':
			$form = t('Thank you!');
	}
	return $form;
}

function my_form_form_validate($form, &$form_state){
	if (!preg_match("[^.+@.+\..+$]", $form_state['values']['email'])){
		form_set_error('email','You enter wrong mail. Try again.');
	}
	if (!empty($form_state['values']['phone']) && !is_numeric($form_state['values']['phone'])){
		form_set_error('phone','Please enter a valid phone number.');
	}
}

function my_form_form_submit($form, &$form_state){
	$form_state['redirect'] = 'success';
}

